// Generates the curriculum the app renders from the three files at the root of
// this repository that already define LAUNCHPAD:
//
//   curriculum-ai.js             the graph: modules, gates, checkpoints, words,
//                                tracks, the plan arithmetic
//   AI_ENGINEERING_CURRICULUM.md the prose: every module written out in full,
//                                plus the rules, the bets and the appendices
//   launchpadviz.js              one mechanism figure per module
//
// Nothing is copied into the app by hand. The curriculum took a long time to
// write and it is written once, up there; test/drift.js keeps the markdown and
// the JS agreeing, and this script is the only bridge from them to the app. So
// an edit to either file reaches the app on the next build and cannot reach it
// any other way.
//
// Outputs, all generated and ignored by git:
//   src/curriculum/generated/launchpad-data.js   curriculum-ai.js verbatim, as an ES module
//   src/curriculum/generated/launchpad-viz.js    the figures, as an ES module
//   src/curriculum/generated/launchpad-doc.js    the document's non-module sections
//   src/curriculum/lessons/<M id>/*.md           each module's prose, as lessons
//
// Run with plain Node 22: `node scripts/launchpad-curriculum.ts`. Every npm
// script that builds, checks or tests runs it first.
import fs from 'node:fs'
import path from 'node:path'
import vm from 'node:vm'
import { fileURLToPath } from 'node:url'

const app = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const repo = path.resolve(app, '..')
const out = path.join(app, 'src', 'curriculum', 'generated')
const lessonsDir = path.join(app, 'src', 'curriculum', 'lessons')

const SRC_JS = fs.readFileSync(path.join(repo, 'curriculum-ai.js'), 'utf8')
const SRC_MD = fs.readFileSync(path.join(repo, 'AI_ENGINEERING_CURRICULUM.md'), 'utf8').replace(/\r\n/g, '\n')
const SRC_VIZ = fs.readFileSync(path.join(repo, 'launchpadviz.js'), 'utf8')

/** Writes only when the content changed, so a rebuild does not churn mtimes. */
function write(file: string, body: string) {
  fs.mkdirSync(path.dirname(file), { recursive: true })
  if (fs.existsSync(file) && fs.readFileSync(file, 'utf8') === body) return
  fs.writeFileSync(file, body)
}

/* ── 1. The graph, verbatim ────────────────────────────────────────────────
   The file is loaded as-is and only given an export line. Its functions — the
   plan arithmetic, the hard gate, the critical path, validate() — therefore run
   in the app exactly as they ran in the old realm, rather than as a port that
   could quietly disagree with them. */
const EXPORTS = [
  'AI_CURRICULUM', 'AI_LAYERS', 'AI_TRACKS', 'LAUNCHPAD_CONFIG', 'AI_OWNED_CONCEPTS',
  'AI_SPIRAL_PAIRS', 'AI_OWNED_ONCE', 'AI_OWNED_THEN_DEEPENED', 'LAUNCHPAD_RULES',
  'AI_COMPRESSED_SPINE', 'AI_CUT_ORDER', 'AI_CURRICULUM_API', 'AI_DETAIL', 'AI_WORDS',
  'AI_CHECKPOINTS', 'AI_SPINE_TRACK_HOURS',
]
write(
  path.join(out, 'launchpad-data.js'),
  '// Generated by scripts/launchpad-curriculum.ts from ../curriculum-ai.js — do not edit.\n' +
    '/* eslint-disable */\n' +
    // The file exports itself to Node through `module.exports` behind a
    // `typeof module` guard. Shadowing the name keeps that guard false here
    // without editing a line of the file, and keeps the bundler from treating
    // an ES module as CommonJS.
    'var module = undefined;\n' +
    SRC_JS +
    `\nexport { ${EXPORTS.join(', ')} }\n`,
)

// The same file evaluated here, for the lesson split below. A CommonJS shim is
// enough: the file already exports itself to Node.
const sandbox: { module: { exports: Record<string, unknown> } } = { module: { exports: {} } }
vm.runInNewContext(SRC_JS, sandbox)
const C = sandbox.module.exports as {
  AI_CURRICULUM: { id: string; title: string; concepts?: string[] }[]
}

/* ── 2. The figures ─────────────────────────────────────────────────────── */
const vizBox: { window: { LAUNCHPAD_VIZ?: Record<string, string> } } = { window: {} }
vm.runInNewContext(SRC_VIZ, vizBox)
const VIZ = vizBox.window.LAUNCHPAD_VIZ ?? {}
write(
  path.join(out, 'launchpad-viz.js'),
  '// Generated by scripts/launchpad-curriculum.ts from ../launchpadviz.js — do not edit.\n' +
    `export const LAUNCHPAD_VIZ = ${JSON.stringify(VIZ)}\n`,
)

/* ── 3. The prose ────────────────────────────────────────────────────────
   The document is cut at its top two heading levels. A `## M<n> — ` section is
   a module; everything else is a section of the document itself (the numbers,
   the rules, the hard gate, the tracks, the appendices), which the Guide and
   the Reference page read. */
interface Section {
  level: 1 | 2
  heading: string
  body: string
}

const sections: Section[] = []
{
  let cur: Section | null = null
  let fence = false
  for (const line of SRC_MD.split('\n')) {
    if (line.trim().startsWith('```')) fence = !fence
    const h = !fence ? /^(#{1,2}) (.+)$/.exec(line) : null
    if (h) {
      if (cur) sections.push(cur)
      cur = { level: h[1]!.length as 1 | 2, heading: h[2]!.trim(), body: '' }
      continue
    }
    if (cur) cur.body += line + '\n'
  }
  if (cur) sections.push(cur)
}

/** Strips the trailing horizontal rule a section ends on, and blank edges. */
function tidy(body: string): string {
  return body.replace(/\n+-{3,}\s*$/, '').replace(/^\n+|\n+$/g, '') + '\n'
}

function minutes(text: string): number {
  const words = text.split(/\s+/).filter((w) => /[A-Za-z0-9]/.test(w)).length
  return Math.max(1, Math.round(words / 200))
}

/** Wraps a header value in quotes the lesson parser strips verbatim (it does
    not unescape), choosing whichever quote the text does not contain. */
function yamlQuote(s: string): string {
  if (!s.includes('"')) return `"${s}"`
  if (!s.includes("'")) return `'${s}'`
  return s
}

// Module sections → lessons. Each module's prose is split at its GATE
// paragraph: what the module teaches and asks you to build, then the gate and
// what most people get wrong. Nothing is rewritten; the two files together are
// the section exactly as the document has it.
const moduleSections = new Map<string, string>()
for (const s of sections) {
  const m = /^(M\d+) — /.exec(s.heading)
  if (s.level === 2 && m) moduleSections.set(m[1]!, tidy(s.body))
}

// Start clean, so a module removed from the document leaves no stale lesson.
for (const d of fs.existsSync(lessonsDir) ? fs.readdirSync(lessonsDir) : []) {
  const full = path.join(lessonsDir, d)
  if (/^M\d+$/.test(d) && fs.statSync(full).isDirectory()) {
    const keep = moduleSections.has(d)
    if (!keep) fs.rmSync(full, { recursive: true })
  }
}

const missing: string[] = []
for (const mod of C.AI_CURRICULUM) {
  const body = moduleSections.get(mod.id)
  if (!body) {
    missing.push(mod.id)
    continue
  }
  const covers = mod.concepts && mod.concepts.length ? mod.concepts : [mod.title]
  const at = body.search(/^\*\*GATE\*\*/m)
  const parts: { slug: string; title: string; text: string }[] =
    at > 0
      ? [
          { slug: 'the-module', title: `${mod.title} — what to understand and what to build`, text: body.slice(0, at) },
          { slug: 'the-gate', title: `${mod.title} — the gate, and what most people miss`, text: body.slice(at) },
        ]
      : [{ slug: 'the-module', title: mod.title, text: body }]

  const dir = path.join(lessonsDir, mod.id)
  const wanted = new Set<string>()
  parts.forEach((p, i) => {
    const file = `${String(i + 1).padStart(2, '0')}-${p.slug}.md`
    wanted.add(file)
    const text = tidy(p.text)
    const header = [
      '---',
      `id: ${mod.id.toLowerCase()}-${p.slug}`,
      `title: ${yamlQuote(p.title)}`,
      `minutes: ${minutes(text)}`,
      'covers:',
      ...covers.map((c) => `  - ${yamlQuote(c)}`),
      '---',
      '',
    ].join('\n')
    write(path.join(dir, file), header + text)
  })
  for (const f of fs.existsSync(dir) ? fs.readdirSync(dir) : []) {
    if (!wanted.has(f)) fs.rmSync(path.join(dir, f))
  }
}
if (missing.length) {
  console.error(`launchpad-curriculum: no section in the document for ${missing.join(', ')}`)
  process.exit(1)
}

// Everything that is not a module or a layer banner is a document section.
interface DocSection {
  id: string
  title: string
  /** The `#` heading it sits under, for grouping. */
  part: string
  markdown: string
}
const doc: DocSection[] = []
{
  let part = ''
  const used = new Set<string>()
  for (const s of sections) {
    if (s.level === 1) part = s.heading
    if (s.level === 2 && /^M\d+ — /.test(s.heading)) continue
    if (s.level === 1 && /^LAYER \d+ — /.test(s.heading)) continue
    const markdown = tidy(s.body)
    if (!markdown.trim()) continue
    let id = s.heading
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-|-$/g, '')
    while (used.has(id)) id += '-2'
    used.add(id)
    doc.push({ id, title: s.heading.replace(/^▲\s*/, ''), part, markdown })
  }
}
write(
  path.join(out, 'launchpad-doc.js'),
  '// Generated by scripts/launchpad-curriculum.ts from ../AI_ENGINEERING_CURRICULUM.md — do not edit.\n' +
    `export const LAUNCHPAD_DOC = ${JSON.stringify(doc, null, 1)}\n`,
)

console.log(
  `launchpad-curriculum: ${C.AI_CURRICULUM.length} modules, ${moduleSections.size} module sections, ` +
    `${doc.length} document sections, ${Object.keys(VIZ).length} figures`,
)
