// Regenerates src/curriculum/lessons/manifest.ts from the lesson files on disk.
// Run with plain Node 22 (type stripping): `node scripts/lessons-manifest.ts`,
// or `npm run lessons:manifest`. The build runs it first, so a stale manifest
// cannot ship; the validator test fails if the committed one drifts.
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { parseLesson } from '../src/curriculum/lessons/parse.ts'
import { AI_CURRICULUM } from '../src/curriculum/generated/launchpad-data.js'

// The generated curriculum rather than src/curriculum/index.ts: that module
// attaches lessons via import.meta.glob, which only exists under Vite, and this
// script has to run under plain Node so the build can regenerate before
// bundling. A module's topics are its concepts, exactly as launchpad.ts maps
// them; scripts/launchpad-curriculum.ts runs first and writes that file.
const TOPICS = new Map<string, string[]>(
  (AI_CURRICULUM as { id: string; title: string; concepts?: string[] }[]).map((m) => [
    m.id,
    m.concepts && m.concepts.length ? m.concepts : [m.title],
  ]),
)

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const dir = path.join(root, 'src', 'curriculum', 'lessons')

export interface ManifestEntry {
  id: string
  title: string
  minutes: number
  covers: string[]
  file: string
}

/**
 * How much of a module the written lessons actually teach. Derived, never
 * hand-maintained: a module is complete exactly when its lessons' `covers`
 * entries account for every topic the module lists.
 *
 * This exists so the app can be honest while the corpus is still being
 * written. A module with four of eleven topics taught says so on its card
 * instead of presenting a half-written module as the finished article.
 */
export interface CoverageEntry {
  covered: number
  total: number
  complete: boolean
  /** Topics no lesson covers yet, verbatim. */
  missing: string[]
}

export function buildManifest(): Record<string, ManifestEntry[]> {
  const out: Record<string, ManifestEntry[]> = {}
  for (const moduleId of fs.readdirSync(dir).sort((a, b) => a.localeCompare(b, 'en', { numeric: true }))) {
    const modDir = path.join(dir, moduleId)
    if (!fs.statSync(modDir).isDirectory()) continue
    const files = fs.readdirSync(modDir).filter((f) => f.endsWith('.md')).sort()
    if (files.length === 0) continue
    out[moduleId] = files.map((file) => {
      const { header } = parseLesson(fs.readFileSync(path.join(modDir, file), 'utf8'), `${moduleId}/${file}`)
      return { ...header, file: `${moduleId}/${file}` }
    })
  }
  return out
}

export function buildCoverage(
  manifest: Record<string, ManifestEntry[]> = buildManifest(),
): Record<string, CoverageEntry> {
  /*
   * Every module in the curriculum gets an entry, including the ones with no
   * lessons at all.
   *
   * That is the whole point. Reporting only the modules that happen to have a
   * directory on disk means a module nobody has written yet is indistinguishable
   * from one that needs no lessons, and the app then shows her a page full of
   * objectives with no hint that the teaching is missing. A learner cannot plan
   * around a gap she cannot see. An entry reading nought of thirteen is the
   * honest answer and the UI can say so plainly.
   */
  const out: Record<string, CoverageEntry> = {}
  for (const [moduleId, topics] of TOPICS) {
    const lessons = manifest[moduleId] ?? []
    const covered = new Set<string>()
    for (const l of lessons) for (const c of l.covers) if (topics.includes(c)) covered.add(c)
    const missing = topics.filter((t) => !covered.has(t))
    out[moduleId] = {
      covered: covered.size,
      total: topics.length,
      complete: missing.length === 0,
      missing,
    }
  }
  return out
}

export function renderManifest(
  manifest: Record<string, ManifestEntry[]>,
  coverage: Record<string, CoverageEntry> = buildCoverage(manifest),
): string {
  return [
    '// Generated by scripts/lessons-manifest.ts — do not edit by hand.',
    '// Lesson metadata for every module that has lessons on disk; bodies load lazily.',
    "import type { LessonMeta } from './types'",
    '',
    `export const LESSON_MANIFEST: Record<string, LessonMeta[]> = ${JSON.stringify(manifest, null, 2)}`,
    '',
    '/** Derived: how much of each module its lessons actually teach. */',
    'export interface LessonCoverage {',
    '  covered: number',
    '  total: number',
    '  complete: boolean',
    '  missing: string[]',
    '}',
    '',
    `export const LESSON_COVERAGE: Record<string, LessonCoverage> = ${JSON.stringify(coverage, null, 2)}`,
    '',
  ].join('\n')
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const manifest = buildManifest()
  const coverage = buildCoverage(manifest)
  const target = path.join(dir, 'manifest.ts')
  const body = renderManifest(manifest, coverage)
  if (!fs.existsSync(target) || fs.readFileSync(target, 'utf8') !== body) fs.writeFileSync(target, body)
  const lessons = Object.values(manifest).reduce((a, l) => a + l.length, 0)
  const all = Object.values(coverage)
  const done = all.filter((c) => c.complete).length
  const untouched = all.filter((c) => c.covered === 0).length
  const topics = all.reduce((a, c) => a + c.covered, 0)
  const totalTopics = all.reduce((a, c) => a + c.total, 0)
  // Reported against the whole curriculum rather than against the folders that
  // happen to exist, so the number never flatters the state of the work.
  console.log(
    `lessons-manifest: ${lessons} lessons · ${done}/${all.length} modules fully taught · ` +
      `${topics}/${totalTopics} topics · ${untouched} modules not started ` +
      `→ ${path.relative(root, target)}`,
  )
}
